/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.UI;

import com.mycompany.Business.PessoaBusiness;
import com.mycompany.Business.ProjetoBusiness;
import com.mycompany.Business.RequisitoBusiness;
import com.mycompany.Model.Pessoa;
import com.mycompany.Model.Projeto;
import com.mycompany.Model.Requisito;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 *
 * @author Familia
 */
public class GerenciarRequisitoJFrame extends javax.swing.JFrame {

    private PessoaBusiness _pessoaBusiness;
    private ProjetoBusiness _projetoBusiness;
    private RequisitoBusiness _requisitoBusiness;
    private String _finalidadeTela;
    private Projeto _projeto;
    private Requisito _requisito;
    /**
     * Creates new form CadastrarProjetoJFrame
     */
  
    public GerenciarRequisitoJFrame(String finalidadeTela, Projeto projeto, PessoaBusiness pessoaBusiness) {
        initComponents();
        this._projetoBusiness = new ProjetoBusiness();
        this._requisitoBusiness = new RequisitoBusiness();
        this._pessoaBusiness = pessoaBusiness;
        this._finalidadeTela = finalidadeTela;
        this._projeto = projeto;
    }
    
    public GerenciarRequisitoJFrame(String finalidadeTela, Projeto projeto, PessoaBusiness pessoaBusiness, Requisito requisito) {
        this(finalidadeTela, projeto, pessoaBusiness);
        this._requisito = requisito;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        nomejLabel = new javax.swing.JLabel();
        esforcoEmHorasjTextField = new javax.swing.JTextField();
        nomejTextField = new javax.swing.JTextField();
        esforcoEmHorasjLabel = new javax.swing.JLabel();
        descricaojLabel = new javax.swing.JLabel();
        fasejTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricaojTextArea = new javax.swing.JTextArea();
        fasejLabel = new javax.swing.JLabel();
        prioridadejComboBox = new javax.swing.JComboBox<>();
        modulojTextField = new javax.swing.JTextField();
        complexidadejComboBox = new javax.swing.JComboBox<>();
        modulojLabel = new javax.swing.JLabel();
        estadojLabel = new javax.swing.JLabel();
        funcionalidadejTextField = new javax.swing.JTextField();
        estadojComboBox = new javax.swing.JComboBox<>();
        funcionalidadejLabel = new javax.swing.JLabel();
        confirmarjButton = new javax.swing.JButton();
        prioridadejLabel = new javax.swing.JLabel();
        cancelarjButton = new javax.swing.JButton();
        complexidadejLabel = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Requisitos");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel1.setForeground(new java.awt.Color(0, 102, 102));

        nomejLabel.setForeground(new java.awt.Color(0, 0, 0));
        nomejLabel.setText("Nome:");

        esforcoEmHorasjLabel.setForeground(new java.awt.Color(0, 0, 0));
        esforcoEmHorasjLabel.setText("Esforço em Horas:");

        descricaojLabel.setForeground(new java.awt.Color(0, 0, 0));
        descricaojLabel.setText("Descrição:");

        descricaojTextArea.setColumns(20);
        descricaojTextArea.setRows(5);
        jScrollPane1.setViewportView(descricaojTextArea);

        fasejLabel.setForeground(new java.awt.Color(0, 0, 0));
        fasejLabel.setText("Fase:");

        prioridadejComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alta", "Média", "Baixa" }));
        prioridadejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prioridadejComboBoxActionPerformed(evt);
            }
        });

        complexidadejComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Alta", "Média", "Baixa" }));
        complexidadejComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                complexidadejComboBoxActionPerformed(evt);
            }
        });

        modulojLabel.setForeground(new java.awt.Color(0, 0, 0));
        modulojLabel.setText("Modulo:");

        estadojLabel.setForeground(new java.awt.Color(0, 0, 0));
        estadojLabel.setText("Estado:");

        estadojComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não iniciado", "Em andamento", "Concluído", "Paralizado" }));

        funcionalidadejLabel.setForeground(new java.awt.Color(0, 0, 0));
        funcionalidadejLabel.setText("Funcionalidade:");

        confirmarjButton.setText("Cadastrar");
        confirmarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarjButtonActionPerformed(evt);
            }
        });

        prioridadejLabel.setForeground(new java.awt.Color(0, 0, 0));
        prioridadejLabel.setText("Prioridade:");

        cancelarjButton.setText("Cancelar");
        cancelarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarjButtonActionPerformed(evt);
            }
        });

        complexidadejLabel.setForeground(new java.awt.Color(0, 0, 0));
        complexidadejLabel.setText("Complexidade:");

        jPanel2.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cadastro de Requisitos");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(7, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(estadojLabel)
                                .addGap(18, 18, 18)
                                .addComponent(estadojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(fasejLabel)
                                .addGap(18, 18, 18)
                                .addComponent(fasejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(esforcoEmHorasjLabel)
                                .addGap(18, 18, 18)
                                .addComponent(esforcoEmHorasjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(complexidadejLabel)
                                .addGap(18, 18, 18)
                                .addComponent(complexidadejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(prioridadejLabel)
                                .addGap(18, 18, 18)
                                .addComponent(prioridadejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(funcionalidadejLabel)
                                .addGap(18, 18, 18)
                                .addComponent(funcionalidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(modulojLabel)
                                .addGap(18, 18, 18)
                                .addComponent(modulojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(91, 91, 91)
                            .addComponent(cancelarjButton)
                            .addGap(41, 41, 41)
                            .addComponent(confirmarjButton))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(nomejLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(descricaojLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jScrollPane1)
                                .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(143, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomejLabel)
                    .addComponent(nomejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(modulojLabel)
                    .addComponent(modulojTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(funcionalidadejLabel)
                    .addComponent(funcionalidadejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prioridadejLabel)
                    .addComponent(prioridadejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(complexidadejLabel)
                    .addComponent(complexidadejComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(esforcoEmHorasjLabel)
                    .addComponent(esforcoEmHorasjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(estadojLabel)
                    .addComponent(estadojComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fasejLabel)
                    .addComponent(fasejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(descricaojLabel)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelarjButton)
                    .addComponent(confirmarjButton))
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void confirmarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarjButtonActionPerformed
        // TODO add your handling code here:   
        int idProjeto = _projeto.getId_projeto();
        Pessoa pessoa = _pessoaBusiness.getPessoaLogada();
        String username = pessoa.getUsername();
        
        Object prioridadeItem = prioridadejComboBox.getSelectedItem();
        Object complexidadeItem = complexidadejComboBox.getSelectedItem();
        Object estadoItem = estadojComboBox.getSelectedItem();
        String esforcoEmHorasText = esforcoEmHorasjTextField.getText();
        
        Requisito requisito = new Requisito();
        
        String nome = nomejTextField.getText();
        String modulo = modulojTextField.getText();
        String funcionalidade = funcionalidadejTextField.getText();
        float versao = 0;
        String prioridade = (String)prioridadeItem;
        String complexidade = (String)complexidadeItem;
        int esforcoEmHoras = Integer.valueOf(esforcoEmHorasText);
        String estado = (String)estadoItem;
        String fase = fasejTextField.getText();
        String descricao = descricaojTextArea.getText();
        Date dataUltimaAlteracao = new Date();
        String autorUltimaModificacao = username;
        
        requisito.setNome(nome);
        requisito.setModulo(modulo);
        requisito.setFuncionalidade(funcionalidade);
        requisito.setVersao(versao);
        requisito.setPrioridade(prioridade);
        requisito.setComplexidade(complexidade);
        requisito.setEsforcoEmHoras(esforcoEmHoras);
        requisito.setEstado(estado);
        requisito.setFase(fase);
        requisito.setDescricao(descricao);
        requisito.setDataUltimaAlteracao(dataUltimaAlteracao);
        requisito.setAutorUltimaModificacao(autorUltimaModificacao);
        requisito.setIdProjeto(idProjeto);
        
       
        if(_finalidadeTela.equals("Atualizar")){
            System.out.println(idProjeto);
            int idRequisito = _requisito.getId();
            Date dataCriacao = _requisito.getDataCriacao();
            String autor = _requisito.getAutor();
            requisito.setAutor(autor);
            requisito.setDataCriacao(dataCriacao);
            requisito.setId(idRequisito);
            this._requisitoBusiness.Atualizar(requisito);
        }else{
            Date dataCriacao = new Date();
            String autor = username;
            requisito.setAutor(autor);
            requisito.setDataCriacao(dataCriacao);
            this._requisitoBusiness.Adicionar(requisito);
        }
        
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_confirmarjButtonActionPerformed

    private void cancelarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarjButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        this.dispose();
    }//GEN-LAST:event_cancelarjButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        if(_finalidadeTela.equals("Atualizar")){
            confirmarjButton.setText("Atualizar");
            this.setTitle("Atualização de Requisitos");
            jLabel1.setText("Atualizar Requisitos");
            String nome = _requisito.getNome();
            String modulo = _requisito.getModulo();
            String funcionalidade = _requisito.getFuncionalidade();
            String prioridade = _requisito.getPrioridade();
            String complexidade = _requisito.getComplexidade();
            int esforcoEmHorasInt = _requisito.getEsforcoEmHoras();
            String estado = _requisito.getEstado();
            String fase = _requisito.getFase();
            String descricao = _requisito.getDescricao();
            
            //Map<String, String> mapPrioridade = new HashMap<>();
            //mapPrioridade.put("","");
            
            String esforcoEmHoras = String.valueOf(esforcoEmHorasInt);
            int prioridadeItem = 0;
            int complexidadeItem = 0;
            int estadoItem = 0;
            
            nomejTextField.setText(nome);
            modulojTextField.setText(modulo);
            funcionalidadejTextField.setText(funcionalidade);
            prioridadejComboBox.setSelectedItem(prioridade);
            complexidadejComboBox.setSelectedIndex(complexidadeItem);
            esforcoEmHorasjTextField.setText(esforcoEmHoras);
            estadojComboBox.setSelectedIndex(estadoItem);
            fasejTextField.setText(fase);
            descricaojTextArea.setText(descricao);
        } else{
            this.setTitle("Cadastro de Requisitos");
        }
    }//GEN-LAST:event_formWindowActivated

    private void prioridadejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prioridadejComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prioridadejComboBoxActionPerformed

    private void complexidadejComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_complexidadejComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_complexidadejComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelarjButton;
    private javax.swing.JComboBox<String> complexidadejComboBox;
    private javax.swing.JLabel complexidadejLabel;
    private javax.swing.JButton confirmarjButton;
    private javax.swing.JLabel descricaojLabel;
    private javax.swing.JTextArea descricaojTextArea;
    private javax.swing.JLabel esforcoEmHorasjLabel;
    private javax.swing.JTextField esforcoEmHorasjTextField;
    private javax.swing.JComboBox<String> estadojComboBox;
    private javax.swing.JLabel estadojLabel;
    private javax.swing.JLabel fasejLabel;
    private javax.swing.JTextField fasejTextField;
    private javax.swing.JLabel funcionalidadejLabel;
    private javax.swing.JTextField funcionalidadejTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel modulojLabel;
    private javax.swing.JTextField modulojTextField;
    private javax.swing.JLabel nomejLabel;
    private javax.swing.JTextField nomejTextField;
    private javax.swing.JComboBox<String> prioridadejComboBox;
    private javax.swing.JLabel prioridadejLabel;
    // End of variables declaration//GEN-END:variables
}
