/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.UI;

import com.mycompany.Business.PessoaBusiness;
import com.mycompany.Business.ProjetoBusiness;
import com.mycompany.Model.Projeto;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Familia
 */
public class ProjetoJFrame extends javax.swing.JFrame {

    private PessoaBusiness _pessoaBusiness;
    private MenuPrincipalJFrame _menuPrincipal;
    private ProjetoBusiness _projetoBusiness;
    
    /**
     * Creates new form ProjetoJFrame
     */
    public ProjetoJFrame(PessoaBusiness pessoaBusiness, MenuPrincipalJFrame menuPrincipal) {
        initComponents();
        this._pessoaBusiness = pessoaBusiness;
        this._menuPrincipal = menuPrincipal;
        _projetoBusiness = new ProjetoBusiness();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        VoltarjButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        projetojTable = new javax.swing.JTable();
        NovojButton = new javax.swing.JButton();
        DetalharjButton = new javax.swing.JButton();
        AlterarjButton = new javax.swing.JButton();
        ExcluirjButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Gerenciador de Projeto");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        VoltarjButton.setText("Voltar");
        VoltarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarjButtonActionPerformed(evt);
            }
        });

        projetojTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Proprietário", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        projetojTable.getTableHeader().setReorderingAllowed(false);
        projetojTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                projetojTableMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(projetojTable);
        if (projetojTable.getColumnModel().getColumnCount() > 0) {
            projetojTable.getColumnModel().getColumn(1).setMinWidth(100);
            projetojTable.getColumnModel().getColumn(3).setMinWidth(200);
        }

        NovojButton.setText("Novo Projeto");
        NovojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovojButtonActionPerformed(evt);
            }
        });

        DetalharjButton.setText("Detalhar Projeto");
        DetalharjButton.setEnabled(false);
        DetalharjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DetalharjButtonActionPerformed(evt);
            }
        });

        AlterarjButton.setText("Alterar Projeto");
        AlterarjButton.setEnabled(false);
        AlterarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarjButtonActionPerformed(evt);
            }
        });

        ExcluirjButton.setText("Excluir Projeto");
        ExcluirjButton.setEnabled(false);
        ExcluirjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NovojButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DetalharjButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AlterarjButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ExcluirjButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(VoltarjButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 587, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(NovojButton)
                        .addGap(27, 27, 27)
                        .addComponent(DetalharjButton)
                        .addGap(27, 27, 27)
                        .addComponent(AlterarjButton)
                        .addGap(29, 29, 29)
                        .addComponent(ExcluirjButton)
                        .addGap(121, 121, 121)
                        .addComponent(VoltarjButton))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 368, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void NovojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovojButtonActionPerformed
        // TODO add your handling code here:
        //this.setVisible(false);
        GerenciarProjetoJFrame menuCadastrarProjeto = new GerenciarProjetoJFrame(_pessoaBusiness, "Cadastrar");
        menuCadastrarProjeto.setLocationRelativeTo(this);
        menuCadastrarProjeto.setVisible(true);
    }//GEN-LAST:event_NovojButtonActionPerformed

    private void AlterarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarjButtonActionPerformed
        // TODO add your handling code here:
        int idProjeto = getIdProjetoSelecionado();
        System.out.println(idProjeto);
        Projeto projeto = _projetoBusiness.Consultar(idProjeto);
        System.out.println("Teste");
        System.out.println(projeto.getId_projeto());
        GerenciarProjetoJFrame menuCadastrarProjeto = new GerenciarProjetoJFrame(_pessoaBusiness, "Atualizar", projeto);
        menuCadastrarProjeto.setLocationRelativeTo(this);
        menuCadastrarProjeto.setVisible(true);
    }//GEN-LAST:event_AlterarjButtonActionPerformed

    private void ExcluirjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirjButtonActionPerformed
        // TODO add your handling code here:
        int row = projetojTable.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)projetojTable.getModel();
        Object columnId = model.getValueAt(row, 0);
        Integer id = Integer.parseInt(columnId.toString());
        model.removeRow(row);
        _projetoBusiness.Excluir(id);
    }//GEN-LAST:event_ExcluirjButtonActionPerformed

    private void VoltarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarjButtonActionPerformed
        // TODO add your handling code here:
        this.dispose();
        _menuPrincipal.setVisible(true);
    }//GEN-LAST:event_VoltarjButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        List<Projeto> lstProjetos = _projetoBusiness.Listar();
        
        DefaultTableModel model = (DefaultTableModel)projetojTable.getModel();
        Object rowData[] = new Object[4];
        
        model.setRowCount(0);
        
        for (Projeto item : lstProjetos) {
            rowData[0] = item.getId_projeto();
            rowData[1] = item.getNomeProjeto();
            rowData[2] = item.getUsuarioProprietario();
            rowData[3] = item.getDescricao();
            model.addRow(rowData);
        }
        int row = projetojTable.getSelectedRow();
        if(row == -1){
            AlterarjButton.setEnabled(false);
            ExcluirjButton.setEnabled(false);
            DetalharjButton.setEnabled(false);
        } else{
            AlterarjButton.setEnabled(true);
            ExcluirjButton.setEnabled(true);
            DetalharjButton.setEnabled(true);
        }
    }//GEN-LAST:event_formWindowActivated

    private void DetalharjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DetalharjButtonActionPerformed
        // TODO add your handling code here:
        int id = getIdProjetoSelecionado();
        
        Projeto projeto = _projetoBusiness.Consultar(id);
        
        RequisitoJFrame telaRequisito = new RequisitoJFrame(_pessoaBusiness, projeto);
        
        telaRequisito.setLocationRelativeTo(this);
        telaRequisito.setVisible(true);
    }//GEN-LAST:event_DetalharjButtonActionPerformed

    private void projetojTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projetojTableMouseClicked
        // TODO add your handling code here:
        int row = projetojTable.getSelectedRow();
        if(row != -1){
            AlterarjButton.setEnabled(true);
            ExcluirjButton.setEnabled(true);
            DetalharjButton.setEnabled(true);
        }
    }//GEN-LAST:event_projetojTableMouseClicked

    private int getIdProjetoSelecionado(){
        int row = projetojTable.getSelectedRow();
        
        DefaultTableModel model = (DefaultTableModel)projetojTable.getModel();
        Object columnId = model.getValueAt(row, 0);
        Integer id = Integer.parseInt(columnId.toString());
        
        return id;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlterarjButton;
    private javax.swing.JButton DetalharjButton;
    private javax.swing.JButton ExcluirjButton;
    private javax.swing.JButton NovojButton;
    private javax.swing.JButton VoltarjButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable projetojTable;
    // End of variables declaration//GEN-END:variables
}
