/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.UI;

import com.mycompany.Business.PessoaBusiness;
import com.mycompany.Business.ProjetoBusiness;
import com.mycompany.Model.Projeto;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Familia
 */
public class ProjetoJFrame extends javax.swing.JFrame {

    private PessoaBusiness _pessoaBusiness;
    private MenuPrincipalJFrame _menuPrincipal;
    private ProjetoBusiness _projetoBusiness;
    
    /**
     * Creates new form ProjetoJFrame
     */
    public ProjetoJFrame(PessoaBusiness pessoaBusiness, MenuPrincipalJFrame menuPrincipal) {
        initComponents();
        this._pessoaBusiness = pessoaBusiness;
        this._menuPrincipal = menuPrincipal;
        _projetoBusiness = new ProjetoBusiness();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NovojButton = new javax.swing.JButton();
        DetalharjButton = new javax.swing.JButton();
        AlterarjButton = new javax.swing.JButton();
        ExcluirjButton = new javax.swing.JButton();
        VoltarjButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        projetojTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        NovojButton.setText("Novo Projeto");
        NovojButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NovojButtonActionPerformed(evt);
            }
        });

        DetalharjButton.setText("Detalhar Projeto");

        AlterarjButton.setText("Alterar Projeto");
        AlterarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AlterarjButtonActionPerformed(evt);
            }
        });

        ExcluirjButton.setText("Excluir Projeto");
        ExcluirjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirjButtonActionPerformed(evt);
            }
        });

        VoltarjButton.setText("Voltar");
        VoltarjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VoltarjButtonActionPerformed(evt);
            }
        });

        projetojTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Nome", "Proprietário"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        projetojTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane3.setViewportView(projetojTable);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ExcluirjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(DetalharjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(NovojButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AlterarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(VoltarjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(17, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(NovojButton)
                        .addGap(32, 32, 32)
                        .addComponent(DetalharjButton)
                        .addGap(32, 32, 32)
                        .addComponent(AlterarjButton)
                        .addGap(32, 32, 32)
                        .addComponent(ExcluirjButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 105, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(18, 18, 18)))
                .addComponent(VoltarjButton)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
 
    private void NovojButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NovojButtonActionPerformed
        // TODO add your handling code here:
        //this.setVisible(false);
        CadastrarProjetoJFrame menuCadastrarProjeto = new CadastrarProjetoJFrame(_pessoaBusiness);
        menuCadastrarProjeto.setLocationRelativeTo(this);
        menuCadastrarProjeto.setVisible(true);
    }//GEN-LAST:event_NovojButtonActionPerformed

    private void AlterarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AlterarjButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AlterarjButtonActionPerformed

    private void ExcluirjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirjButtonActionPerformed
        // TODO add your handling code here:
        int row = projetojTable.getSelectedRow();
        DefaultTableModel model = (DefaultTableModel)projetojTable.getModel();
        Object columnId = model.getValueAt(row, 0);
        Integer id = Integer.parseInt(columnId.toString());
        model.removeRow(row);
        _projetoBusiness.Excluir(id);
    }//GEN-LAST:event_ExcluirjButtonActionPerformed

    private void VoltarjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VoltarjButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        _menuPrincipal.setVisible(true);
    }//GEN-LAST:event_VoltarjButtonActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        List<Projeto> lstProjetos = _projetoBusiness.Listar();
        
        DefaultTableModel model = (DefaultTableModel)projetojTable.getModel();
        Object rowData[] = new Object[3];
        
        model.setRowCount(0);
        
        for (Projeto item : lstProjetos) {
            rowData[0] = item.getId_projeto();
            rowData[1] = item.getNomeProjeto();
            rowData[2] = item.getUsuarioProprietario();
            model.addRow(rowData);
        }
    }//GEN-LAST:event_formWindowActivated


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AlterarjButton;
    private javax.swing.JButton DetalharjButton;
    private javax.swing.JButton ExcluirjButton;
    private javax.swing.JButton NovojButton;
    private javax.swing.JButton VoltarjButton;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable projetojTable;
    // End of variables declaration//GEN-END:variables
}
