/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.UI;

import java.util.List;
import com.mycompany.Model.Requisito;
import com.mycompany.Model.Projeto;
import com.mycompany.Business.RequisitoBusiness;
import java.util.stream.Collectors;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Kelvin
 */
public class RequisitosRelatorioJFrame extends javax.swing.JFrame {

    private RequisitoBusiness _requisitoBusiness;
    private int _idProjeto;
    private ProjetoRelatorioJFrame _projetoRelatorio;
    private List<Requisito> _lstRequisitos;

    /**
     * Creates new form RequisitosRelatorioJFrame
     */
    public RequisitosRelatorioJFrame(int id, ProjetoRelatorioJFrame projeto) {
        initComponents();
        this._requisitoBusiness = new RequisitoBusiness();
        this._idProjeto = id;
        this._projetoRelatorio = projeto;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtFiltro = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableRequisitosRelatorio = new javax.swing.JTable();
        btnVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLabel1.setText("Filtrar:");

        txtFiltro.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtFiltroKeyReleased(evt);
            }
        });

        tableRequisitosRelatorio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Modulo", "Funcionalidades", "Data Criação", "Autor", "Data Última Alteração", "Autor Última Alteração", "Versão", "Prioridade", "Complexidade", "Esforço em Horas", "Estado", "Fase", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableRequisitosRelatorio.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        jScrollPane1.setViewportView(tableRequisitosRelatorio);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 865, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 399, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVoltar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        _lstRequisitos = _requisitoBusiness.Listar(_idProjeto);

        carregarTabela(_lstRequisitos);
    }//GEN-LAST:event_formWindowOpened

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        this.dispose();
        _projetoRelatorio.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void txtFiltroKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFiltroKeyReleased
        // TODO add your handling code here:
        List<Requisito> lst = null;
        
        lst = _lstRequisitos
                .stream()
                .filter(x -> 
                        x.getNome().toLowerCase().contains(txtFiltro.getText().toLowerCase())
                        || x.getAutor().toLowerCase().contains(txtFiltro.getText().toLowerCase())
                        || x.getEstado().toLowerCase().contains(txtFiltro.getText().toLowerCase())
                ).collect(Collectors.toList());
        
        carregarTabela(lst);
    }//GEN-LAST:event_txtFiltroKeyReleased

    public void carregarTabela(List<Requisito> lst) {
        DefaultTableModel model = (DefaultTableModel) tableRequisitosRelatorio.getModel();
        model.getDataVector().removeAllElements();
        model.fireTableDataChanged();
        Object rowData[] = new Object[14];

        for (Requisito item : lst) {
            rowData[0] = item.getNome();
            rowData[1] = item.getModulo();
            rowData[2] = item.getFuncionalidade();
            rowData[3] = item.getDataCriacao();
            rowData[4] = item.getAutor();
            rowData[5] = item.getDataUltimaAlteracao();
            rowData[6] = item.getAutorUltimaModificacao();
            rowData[7] = item.getVersao();
            rowData[8] = item.getPrioridade();
            rowData[9] = item.getComplexidade();
            rowData[10] = item.getEsforcoEmHoras();
            rowData[11] = item.getEstado();
            rowData[12] = item.getFase();
            rowData[13] = item.getDescricao();
            model.addRow(rowData);
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVoltar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableRequisitosRelatorio;
    private javax.swing.JTextField txtFiltro;
    // End of variables declaration//GEN-END:variables
}
