/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.mycompany.UI;

import com.mycompany.Business.PessoaBusiness;
import javax.swing.JOptionPane;

/**
 *
 * @author Familia
 */
public class TrocarSenhaJFrame extends javax.swing.JFrame {
    
    private PessoaBusiness _pessoaBusiness;
    private LoginJFrame _loginJFrame;

    /**
     * Creates new form TrocarSenhaJFrame
     */
    public TrocarSenhaJFrame(PessoaBusiness pessoaBusiness, LoginJFrame loginJFrame) {
        initComponents();
        this._pessoaBusiness = pessoaBusiness;
        this._loginJFrame = loginJFrame;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        senhaLabel = new javax.swing.JLabel();
        senhaField = new javax.swing.JPasswordField();
        senhaRepetidaField = new javax.swing.JPasswordField();
        senhaRepetidaLabel = new javax.swing.JLabel();
        confirmarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Atualizar senha");
        setBackground(new java.awt.Color(153, 153, 153));
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        senhaLabel.setForeground(new java.awt.Color(0, 0, 0));
        senhaLabel.setText("Nova senha:");

        senhaRepetidaField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                senhaRepetidaFieldActionPerformed(evt);
            }
        });
        senhaRepetidaField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                senhaRepetidaFieldKeyPressed(evt);
            }
        });

        senhaRepetidaLabel.setForeground(new java.awt.Color(0, 0, 0));
        senhaRepetidaLabel.setText("Repita a senha:");

        confirmarButton.setText("Confirmar");
        confirmarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(senhaRepetidaLabel)
                            .addComponent(senhaLabel))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(senhaRepetidaField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(senhaField, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(confirmarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(67, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(senhaLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(senhaRepetidaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(senhaRepetidaLabel))
                .addGap(47, 47, 47)
                .addComponent(confirmarButton)
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void senhaRepetidaFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_senhaRepetidaFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaRepetidaFieldActionPerformed

    private void confirmarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmarButtonActionPerformed
        // TODO add your handling code here:
        String senha = senhaField.getText();
        String validaSenha = senhaRepetidaField.getText();
        boolean response = this._pessoaBusiness.trocarSenha(senha, validaSenha);
        
        if(response){
            _loginJFrame.setVisible(false);
            this.setVisible(false);
            MenuPrincipalJFrame telaPrincipal = new MenuPrincipalJFrame(_pessoaBusiness);
            telaPrincipal.setLocationRelativeTo(this);
            telaPrincipal.setVisible(true);
            _loginJFrame.dispose();
            this.dispose();
        }else{
            JOptionPane.showMessageDialog(null, "Senha incompativeis.");
        }
    }//GEN-LAST:event_confirmarButtonActionPerformed

    private void senhaRepetidaFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_senhaRepetidaFieldKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_senhaRepetidaFieldKeyPressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton confirmarButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField senhaField;
    private javax.swing.JLabel senhaLabel;
    private javax.swing.JPasswordField senhaRepetidaField;
    private javax.swing.JLabel senhaRepetidaLabel;
    // End of variables declaration//GEN-END:variables
}
